# Generated by Django 2.2.2 on 2019-08-12 16:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import events.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('wedding', 'wedding'), ('birthday', 'birthday'), ('graduate', 'graduate'), ('wedding', 'wedding'), ('wedding', 'wedding'), ('other', 'other')], default='other', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('code', autoslug.fields.AutoSlugField(editable=False, max_length=5, populate_from='name', unique=True)),
                ('isPublic', models.BooleanField(default=False)),
                ('board', models.OneToOneField(default=events.models.Board.get_new, on_delete=django.db.models.deletion.CASCADE, to='events.Board')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Category')),
            ],
        ),
    ]
