# Generated by Django 2.2.2 on 2019-08-12 16:46

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190812_1809'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='events/background_images/%Y/%m/%d/'),
        ),
    ]
