# Generated by Django 2.2.2 on 2019-08-13 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_like_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('wedding', 'wedding'), ('birthday', 'birthday'), ('graduate', 'graduate'), ('wedding', 'wedding'), ('wedding', 'party'), ('other', 'other')], default='other', max_length=15),
        ),
    ]
