# Generated by Django 2.2.2 on 2019-09-30 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20190929_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmessage',
            name='board',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='events.Board'),
            preserve_default=False,
        ),
    ]
