# Generated by Django 2.2.2 on 2019-11-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_boardmessage_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='code',
        ),
    ]
