# Generated by Django 2.2.2 on 2019-11-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20191110_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='code',
        ),
    ]
